### PR TITLE
Issue #22

### PR DESCRIPTION
**Pull request by mayurdw**
Partial fix which ignores arrow, escape and non alphanumeric characters. 

I didn't fix the character limit issue as it seemed like a separate issue. If I change the file the name is more than 18 chars long, scoreboard breaks. I will try to find a better solution there.

### CODE REVIEW

**Comment by plibither8** [comment]
Cool! It'd be great if you could run clang-format on the code :smile:.

**Comment by plibither8** [comment]
See #29.

**Comment by mayurdw** [comment]
I pulled in the commits that my fork was missing and then updated my master. Github seems to have to resolved all of the merge conflicts .

**Comment by tcoyvwac** [comment]
Hi, this PR will close because the PR's code differs from the main codebase a lot. :mag:
If the issue in the project and the solution still exist, please make a new PR using the latest copy of the codebase.
Thanks! :cat2:

**Pull request closed without merging**
