### PR TITLE
Changed enums to enums classes

### PR DESCRIPTION
**Pull request by VinceBackpack**
Changed enums from the following files:
game.hpp
game.cpp
gameboard.cpp

### CODE REVIEW

**Comment by plibither8** [comment]
Hi! Thanks for your contribution :)

There is a major codebase refactor going on, due to which your PR branch is a few commits _behind_ the `master` branch. Please rebase first before adding to the code :)

Also, we are using `clang-format` to lint and format the C++ code. Before pushing changes, run `clang-format` on the `.cpp` and `.hpp` files.

**Comment by cawvyoct** [comment]
Hi @VinceBackpack, thanks for your PR!
As @plibither8 said, there is a refactoring-drive at the moment so `master` branch is often updated. Please make sure to have the latest `upstream` `master` merged with your own `origin`'s `master` branch.

As for the PR itself, I understand the intention.
Please note however that there is a difference between something being _"strongly typed"_ and something which is _"strongly scoped"_. 
The two both help the same thing: _encapsulation_, but the two are not the same (in an attribute-sense).

**Comment by cawvyoct** [comment]
### Example (Scoping):
Here is an example for code which needs to be "strongly scoped":
```cpp
enum {PERSON1_ID, PERSON2_ID, PERSON3_ID};
enum {ADMIN_ID, BOT_ID, PERSON1_ID};
```

This code will fail because the enum value `PERSON1_ID` is declared twice but if a person used the value `PERSON1_ID`, what would value should it be (`0` or `2`)? 
To quickly solve this issue, one should "scope" the enums.

```cpp
enum classroom {PERSON1_ID, PERSON2_ID, PERSON3_ID};
enum system {ADMIN_ID, BOT_ID, PERSON1_ID};
```
Now, the intent is clearer. `classroom::PERSON1_ID` value is `0` and for `system::PERSON1_ID`, the value is `2`. 
_The **scope's context** (of the enum value) has been strongly defined._

**Comment by tcoyvwac** [comment]
Hi @VinceBackpack, I'm sorry you never received an update! :cat2:

if you use `enum class [...]`, you must use the full namespace scope of the enum value.

For example:
```cpp
enum class abc {
  FIELD_VALUE
};
```
```cpp
enum xyz {
  FIELD_VALUE
};
```
In this example:
To use the value stored in `abc`, you must write `abc::FIELD_VALUE`.
However, to use the value in `xyz`, one only needs to write `FIELD_VALUE`.

Beware! The `FIELD_VALUE` datatype are different from each other in the example enums.

`abc::FIELD_VALUE` is of datatype `abc` and `xyz::FIELD_VALUE` is of datatype `int`!

That is why you get a compiler error.

**Comment by tcoyvwac** [comment]
Please note, this PR will be closed because the PR's code differs from the main codebase a lot. :mag:
If the issue in the project and the solution still exist, please make a new PR using the latest copy of the codebase.
Thanks! :cat2:

**Pull request closed without merging**
