### PR TITLE
Change file structure and update build method

### LINKED ISSUE #30: Better directory structure for project
I feel like the current structure of files and directories is inefficient and not clean. There should be better management of the source files and the build files, rather than all of them being in the root directory.

I am comparatively inexperienced with how larger C++ projects handle directory management. It would be great if a better management is suggested, and better yet, I'd welcome all PRs that implement such a structure. Thanks.

### PR DESCRIPTION
**Pull request by jhugobb**
Resolves #30 

* It now has a dependency on [cmake](https://cmake.org/)
* Adding new files and headers now does not require modification of build file
* Updated README.md with new instructions
* Removed old Makefile as it was unnecessary

### CODE REVIEW

**Comment by jhugobb** [comment]
I have no idea why the image Visual Studio 2017 doesn't pass the test, the ubuntu one is alright, but for some reason there is no Makefile generated after running cmake on that image.

**Comment by plibither8** [comment]
@jhugobb I have updated the master with new commits, please pull them to your branch. Also, is there a possible workaround to make the test pass?

**Comment by jhugobb** [comment]
I'll pull the changes to this branch today, but it is my opinion that your continuous integration is not achieving much of anything right now, it is just checking if it compiles and builds and executable. I'd recommend creating unit tests using some frameworks of c++, and coverage tests as well.
I don't think there is a workaround, but maybe an option I'm missing, I'll look into it today as well.

**Comment by plibither8** [comment]
I removed the Visual Studio 2017 image from the test, you're right: it's not achieving much right now.

**Comment by plibither8** [comment]
@jhugobb what's the status? :smile:

**Comment by jhugobb** [comment]
Unfortunately my schedule is a bit of a mess. As soon as I can I'll make the necessary modifications.

**Comment by plibither8** [comment]
Sure, no problem! :)

**Pull request closed without merging**
