### PR TITLE
Fix: Game::board: Encapsulate datamember into its own class

### PR DESCRIPTION
**Pull request by cawvyoct**
Part of a bigger "Single responsibility principle" (SRP) refactor effort.

1: https://en.wikipedia.org/wiki/Single_responsibility_principle

### CODE REVIEW

**Comment by plibither8** [comment]
@cawvyoct great work! Looked through the code and it seems pretty neat.

I've invited you to be a collaborator of this project. I think it's more appropriate if SRP refactoring has a separate branch which we can merge later altogether.

**Comment by cawvyoct** [comment]
Ahh, I am really honoured to be a collaborator, however for reasons I can't explain :crying_cat_face: , I am unable to accept the position.

Will this be a problem long-term with me submitting to the project?

**Comment by plibither8** [comment]
No problem, I completely understand :sweat_smile:!

No, there is no problem whatsoever with you contributing to this project. In fact I am really grateful for all your contributions 😀

**Comment by cawvyoct** [comment]
Hi, heads up, saw your post on `"another"` site. 
 Should get a `"direct@message"` from me soon to suggest some things and to give advice _(on the project)_.

**Pull request merged**
