### PR TITLE
Added Saving Game State and Continuing Funtionality

### PR DESCRIPTION
**Pull request by farazxameer**
The Continue funtionality works good but currently for continue game we are not saving the stats.

### CODE REVIEW

**Comment by plibither8** [comment]
This seems great! Thanks a lot :)

There are a few bugs though (minor ones) which should be addressed before your branch is merged. If there are no saved games and the option to continue from a saved game is chosen from the menu, a floating point error is thrown and the program exits with and error code. A simple prerequisite check for the existence of the files should be implemented.

I agree that statistics for a continued game should not be saved, it will amount to cheating in a sort of way. Apart from that, it looks all good, thanks :)

**Comment by farazxameer** [comment]
Ohh ya the file check was in my mind, but i forgot to implement that, I'll add the file checking logic.

**Comment by farazxameer** [comment]
I have added the file check and, revamped the startGame function logic, I changed the recursion call and added a loop to get the board size.

**Comment by plibither8** [comment]
Great work! Thank you :)

**Pull request merged**
