### PR TITLE
Fix: Convert Menu class to a namespaced area

### PR DESCRIPTION
**Pull request by cawvyoct**
This PR cleans up the API to call the _"Main Menu"_ for _2048.cpp_.

One only just needs to add `menu.hpp` and to call `Menu::startMenu()`.

For example:
```cpp
#include "menu.hpp"
int main() {
  Menu::startMenu();
}
```

Functions needed for the _2048.cpp's Main Menu_ are contained within _(menu.cpp's)_ own anonymous namespace.

### CODE REVIEW

**Comment by cawvyoct** [comment]
The PR will be closed via _"Squash and Merge"_. :card_file_box:
_(Will be automatically merged in <24hrs from this message if no objections)_

**Comment by cawvyoct** [comment]
As there are no objections, will do squash and merge.

**Comment by plibither8** [comment]
Hi @cawvyoct! Apologies for not replying earlier: was busy this whole week :sweat_smile:.

I looked over the code, and everything looks fine to me :+1:. Just one question: why is using an anonymous namespace a better choice here than a class?

Also, this might be pedantic, but I guess the correct word is "erroneous" as opposed to "errornous" [here](https://github.com/cawvyoct/2048.cpp/blob/f41336eb05bc259f9629d1518894156661a6e24d/src/menu.cpp#L24). :grimacing:

**Comment by cawvyoct** [comment]
> Also, this might be pedantic, but I guess the correct word is "erroneous" as opposed to "errornous" here. :grimacing: 

Yes, you are right.
Thinking about it, "_invalid_" would be a better word (in my opinion) so it should be,  `FlagInputInvalidChoice`.

**Comment by cawvyoct** [comment]
> Just one question: why is using an anonymous namespace a better choice here than a class?

This is a great question! :+1: :smile_cat:
It is a little bit hard to answer in a condensed form so I apologise for the upcoming answer...
_(Will this edit answer to add more clarity / edit mistakes if needed)._ :pen: 

---
However, in a basic summary form,
* A `class` is _normally_ associated as some sort of _"named datastructure"_.
* This `class` did not hold any _"datatypes"_ it wanted to _encapusulate_, so it would be better suited as a `struct`.
* Even as a `struct`, there was no _"datatypes"_ it wanted to combine / rename into a special _"named datastructure"_.
* The _"functions"_ inside of this datastructure would be better suited outside of the `struct` as the _named datastructure_ was acting more like an _API_ to _invoke_ _"something"_.
_Namespaces_ are better suited for this role.
* Items in a _header file_ (`menu.hpp` in this case) are normally intended to be _imported_ (and possibly _invoked_) by other parts of a project's source code.
* _All the functions_ in the _header file_ except one, `startMenu()`, are _not invoked_ anywhere else outside of `menu.cpp` (_its local translation unit_)
* The _original intent of all functions_ except `startMenu()` was to _be hidden_ in the _private_ part of its _class definition_ so _privacy of the API was important_.
* "_Private functions_" like these should be defined in an _unnamed (anonymous) namespace_ in its _translation unit_ and not in the _header file_. This prevents _"anyone"_ from allowing usage of the functions outside of _its local translation unit_.

**Pull request merged**
