### PR TITLE
Translate game

### PR DESCRIPTION
**Pull request by yhjsoar**
We translated the game to Korean and add function to select English or Korean from the first start screen.

### CODE REVIEW

**Comment by cawvyoct** [comment]
:writing_hand:  We like this PR because multi-language support is important to us. :world_map: 

We are trying to refactor the project right now to make it easier for PRs like this one to start adding multiple languages to the project. 
Please note however that adding multiple languages into C++ projects is quite a challenge. We are thinking of ways to support the feature so that it is easy for anyone to add new languages quickly. :dove:

**Comment by cawvyoct** [comment]
Currently, we have come to the decision that using hard-coded `if()` statements blocks would not be wise method of supporting multiple languages. 

This is because:
* it will be difficult to scale (for 10+ languages)
* the code needed will be difficult to support in the projects' lifecycle after long periods of time.

**Comment by cawvyoct** [comment]
This PR will not be merged and will be closed as it does not fit the answer the project needs right now.

However, it is great that you brought it to our attention! :tada: 
It is exciting to see that this game is being played around the world so thank you for your contribution! :world_map: 

I have made a new issue (#89) and have used this PR as reference. 
It will help in finding a solution to the hurdle, ok?
Thanks! :smile:  :+1:

**Comment by yhjsoar** [comment]
Thank You for your answer! 😄

**Pull request closed without merging**
