### PR TITLE
Make Color to be scoped enumeration

### PR DESCRIPTION
**Pull request by tiendq**
Highly recommended http://www.stroustrup.com/C++11FAQ.html#enum

### CODE REVIEW

**Comment by plibither8** [comment]
I read the reference. How are the advantages directly linked to this project? Just asking since I can't get hold of the direct advantages of it 😄.

**Comment by tiendq** [comment]
Short answer, it’s safer then safer code is a pratice we should follow especially it’s easy to do :)

Exactly it’s a new C++ feature that we should use, except you are maintaining an old C code base :)

It says all in this code (copied):

enum class Color { red, blue };   // scoped and strongly typed enum
	                                  // no export of enumerator names into enclosing scope
	                                  // no implicit conversion to int

**Comment by tiendq** [comment]
I'd like to add another link, it's styled better than previous one :). I just found many others `enum` (I didn't look at them yesterday), it's not a high priority task but I suggest you to change them all to `enum class`.

https://isocpp.org/wiki/faq/cpp11-language-types#enum-class

**Comment by plibither8** [comment]
Yes, the second link was more enlightening, thanks :). I see the difference
now, I'll merge the PRs soon.

**Pull request merged**
